antora:
  name: template-tutorial
  dir: gh-pages
  modules:
    - name: index
      label: "Overview"
    - name: module-02
      label: "Step 2"

tabs:
  - name: terminal
    port: 443
    path: /wetty
